baseURL = "https://zulu.inuoe.com/"
defaultContentLanguage = "en-us"
languageCode = "en-us"
title = "Some Catchy Title"

theme = "LoveIt"

[params]
  version = "0.2.X"
  keywords = ["Programming", "Blog"]
  defaultTheme = "auto"
  gitRepo = "https://github.com/Zulu-Inuoe/zulu.git"

  [params.page]
    fontawesome = true

  [params.footer]
    enable = true
    hugo = true
    author = true
    since = 2020
    license = '<a rel="license external nofollow noopener noreffer" href=https://opensource.org/licenses/MIT" target="_blank">MIT</a>'

  [params.home]
    rss = 10

    [params.home.profile]
      enable = true
      gravatarEmail = "zulu.inuoe@gmail.com"
      title = "Wilfredo Velázquez-Rodríguez (Will)"
      subtitle = ""
      social = true

    [params.home.posts]
      enable = true
      paginate = 6

  [params.social]
    github = "Zulu-Inuoe"
    linkedin = "wilfredovelazquez"
    email = "zulu.inuoe@gmail.com"
    rss = true

[author]
  name = "Will"
  email = "zulu.inuoe@gmail.com"

[menu]
  [[menu.main]]
    identifier = "about"
    pre = ""
    post = ""
    name = "About"
    url = "/about/"
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "posts"
    pre = ""
    post = ""
    name = "Posts"
    url = "/posts/"
    title = ""
    weight = 2

[markup]
  [markup.highlight]
    noClasses = false
